compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  deepspeed_config_file: /bd_targaryen/users/clin/relation/config/deepspeed_config.json
  zero3_init_flag: false
distributed_type: No
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
